Repository canonical/canonical-indico-themes, pull requests merged in 2022-09, with the labels that each got.

#5 Update call for abstracts page
  indico_themes_canonical/static/css/ubuntu-summit/_buttons.css
  indico_themes_canonical/static/css/ubuntu-summit/_forms.css
  indico_themes_canonical/static/css/ubuntu-summit/_icons.css
  indico_themes_canonical/static/css/ubuntu-summit/_notifications.css
  indico_themes_canonical/static/css/ubuntu-summit/call-for-abstracts.css
  indico_themes_canonical/static/css/ubuntu-summit/call-for-proposals.css
  indico_themes_canonical/static/css/ubuntu-summit/contribution-list.css
  indico_themes_canonical/static/css/ubuntu-summit/index.css
  indico_themes_canonical/static/css/ubuntu-summit/overview.css
  indico_themes_canonical/static/css/ubuntu-summit/registration.css
  indico_themes_canonical/static/css/ubuntu-summit/scientific-program.css
  indico_themes_canonical/static/css/ubuntu-summit/side-navigation.css
  indico_themes_canonical/static/css/ubuntu-summit/surveys.css
  indico_themes_canonical/static/warning-icon.svg
Labels: Review: Code +1, Review: QA +1

#6 Design update - Overview
  indico_themes_canonical/static/css/ubuntu-summit/_buttons.css
  indico_themes_canonical/static/css/ubuntu-summit/_forms.css
  indico_themes_canonical/static/css/ubuntu-summit/_notifications.css
  indico_themes_canonical/static/css/ubuntu-summit/call-for-abstracts.css
  indico_themes_canonical/static/css/ubuntu-summit/header.css
  indico_themes_canonical/static/css/ubuntu-summit/index.css
  indico_themes_canonical/static/css/ubuntu-summit/overview.css
  indico_themes_canonical/static/css/ubuntu-summit/registration.css
  indico_themes_canonical/static/css/ubuntu-summit/side-navigation.css
  indico_themes_canonical/static/css/ubuntu-summit/surveys.css
  indico_themes_canonical/static/files/information-icon.svg
  indico_themes_canonical/static/js/ubuntu_summit.js
  indico_themes_canonical/static/ubuntu-circle-of-friends-large.png
  indico_themes_canonical/static/warning-icon.svg
  package-lock.json
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#7 Design update 2
  indico_themes_canonical/static/css/ubuntu-summit/_buttons.css
  indico_themes_canonical/static/css/ubuntu-summit/_notifications.css
  indico_themes_canonical/static/css/ubuntu-summit/call-for-abstracts.css
  indico_themes_canonical/static/css/ubuntu-summit/index.css
  indico_themes_canonical/static/css/ubuntu-summit/overview.css
  indico_themes_canonical/static/css/ubuntu-summit/registration.css
  indico_themes_canonical/static/css/ubuntu-summit/surveys.css
Labels: Review: Design needed, Review: Code +1, Review: QA +1

#8 Update top navigation
  indico_themes_canonical/static/css/ubuntu-summit/_buttons.css
  indico_themes_canonical/static/css/ubuntu-summit/_notifications.css
  indico_themes_canonical/static/css/ubuntu-summit/header.css
  indico_themes_canonical/static/css/ubuntu-summit/index.css
  indico_themes_canonical/static/css/ubuntu-summit/overview.css
  indico_themes_canonical/static/css/ubuntu-summit/registration.css
  indico_themes_canonical/static/css/ubuntu-summit/top-navigation.css
  indico_themes_canonical/static/js/ubuntu_summit.js
Labels: Review: Code +1, Review: QA +1

#16 Updates banner & minor fixes
  indico_themes_canonical/static/css/ubuntu-summit/header.css
  indico_themes_canonical/static/css/ubuntu-summit/index.css
  indico_themes_canonical/static/css/ubuntu-summit/overview.css
  indico_themes_canonical/static/css/ubuntu-summit/registration.css
  indico_themes_canonical/static/css/ubuntu-summit/scientific-program.css
  indico_themes_canonical/static/js/ubuntu_summit.js
Labels: Review: Code +1, Review: QA +1

#19 Fixes css conflict causing banner image to block top-nav
  indico_themes_canonical/static/css/ubuntu-summit/header.css
  indico_themes_canonical/static/css/ubuntu-summit/index.css
Labels: Review: Code +1, Review: QA +1

#21 Don't hide buttons to modify registration
  indico_themes_canonical/static/css/ubuntu-summit/_notifications.css
  indico_themes_canonical/static/css/ubuntu-summit/registration.css
Labels: Review: Code +1, Review: QA +1
